PSFR-1844 Add free text fields to Finance and ID pathway
ministryofjustice/hmpps-resettlement-passport-api pull request #576
Opened 2024-11-05 15:23 UTC by abdulrkalam

2024-11-05 16:01 UTC, JamesBoobier requested changes

2024-11-05 16:10 UTC, abdulrkalam commented on src/main/resources/assessment-config/finance-and-id/finance-and-id-assessment-v2.yml
> +        subTitle: ""
Done

2024-11-05 16:10 UTC, abdulrkalam commented on src/main/resources/assessment-config/finance-and-id/finance-and-id-assessment-v2.yml
> +        subTitle: ""
Done

2024-11-06 09:57 UTC, abdulrkalam commented
closed this PR due to merge conflicts!

2024-11-06 09:57 UTC, closed without merging